/*

 BG1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Mr Poopybutthole\Desktop\gameboy\bg1img.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bg1mapWidth 40
#define bg1mapHeight 18
#define bg1mapBank 0

extern unsigned char bg1map[];

/* End of BG1MAP.H */
